version: '3'
services:
  nodejs_app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./dist/data:/path/to/data
    networks:
      - mynetwork
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # 确保你的 Nginx 配置文件被正确挂载到容器中
    depends_on:
      - nodejs_app
    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver: bridge # 定义网络类型