version: '3'
services:
  pixel-server:
    build: .
    volumes:
      - /root/backup_volume:/usr/src/app/dist/data
    networks:
      - main-network
  pixel-server-nginx:
    image: nginx:latest
    ports:
      - "3101:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # 确保你的 Nginx 配置文件被正确挂载到容器中
      - ./var/log/nginx:/var/log/nginx
    depends_on:
      - pixel-server
    networks:
      - main-network
      
networks:
  main-network:
    external: true